### PR TITLE
Allow non-user checking of grayed out checkboxes

### PR DESCRIPTION
**Pull request by Gyoshi**
Hopefully fixes https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/issues/58 (I haven't tested it 🙃) [Inspired by code from these Microsoft Docs](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.treevieweventargs.action?view=netframework-4.6.1#system-windows-forms-treevieweventargs-action)

### CODE REVIEW

**Comment by wooferzfg** [comment]
Can you test it?

**Comment by Gyoshi** [comment]
Uhh so I make the same PR but as a draft instead?

**Comment by Gyoshi** [comment]
I don't know how to, like, 'attach' this code to the livesplit-core?

**Comment by wooferzfg** [comment]
I meant https://github.com/livesplit/livesplit. You can push a branch that updates the submodule to your commit. Or just compile the code and test it locally, up to you.

**Comment by Gyoshi** [comment]
I downloaded the build and it works ☺

**Pull request merged**
